repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.4.9
    hooks:
      # Run the linter, using the config inside pyproject.toml
      - id: ruff
        args: [ "--fix"]
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0  # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
      - id: check-toml
      - id: end-of-file-fixer
